// build.rs — Generate embedded OpenClaw SKILL.md files at compile time.
//
// Scans `../../skills-source/*/SKILL.md` and generates a Rust source file
// containing `include_str!` calls for each skill. The generated file provides
// a function `embedded_skills() -> &'static [(&'static str, &'static str)]`
// returning (skill_name, skill_md_content) pairs.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let skills_dir = PathBuf::from(&manifest_dir).join("../../skills-source");
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("embedded_skills.rs");

    let mut entries = Vec::new();

    if skills_dir.exists() {
        let mut dirs: Vec<_> = fs::read_dir(&skills_dir)
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        dirs.sort_by_key(|e| e.file_name());

        for entry in &dirs {
            let skill_md = entry.path().join("SKILL.md");
            if skill_md.exists() {
                let name = entry.file_name().to_string_lossy().to_string();
                let abs_path = fs::canonicalize(&skill_md).unwrap();
                entries.push((name, abs_path));
            }
        }
    }

    let mut code = String::new();
    code.push_str("/// Auto-generated embedded OpenClaw SKILL.md files.\n");
    code.push_str("/// DO NOT EDIT — regenerated by build.rs.\n\n");

    if entries.is_empty() {
        code.push_str("pub fn embedded_skills() -> &'static [(&'static str, &'static str)] {\n");
        code.push_str("    &[]\n}\n");
    } else {
        code.push_str("pub fn embedded_skills() -> &'static [(&'static str, &'static str)] {\n");
        code.push_str("    &[\n");
        for (name, path) in &entries {
            let escaped_path = path.to_string_lossy().replace('\\', "\\\\");
            code.push_str(&format!(
                "        (\"{}\", include_str!(\"{}\")),\n",
                name, escaped_path
            ));
        }
        code.push_str("    ]\n}\n");
    }

    fs::write(&out_path, code).unwrap();

    // Tell Cargo to rerun if the skills directory changes
    if skills_dir.exists() {
        println!("cargo:rerun-if-changed={}", skills_dir.display());
        for (_, path) in &entries {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
    println!("cargo:rerun-if-changed=build.rs");
}
