apiVersion: v1
kind: Service
metadata:
  name: {{ include "clawdesk.fullname" . }}
  labels:
    {{- include "clawdesk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.clawdesk.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "clawdesk.selectorLabels" . | nindent 4 }}
