//! Content provenance marking — capability-based detection.
//!
//! Replaces substring-matching approaches with capability-based detection
//! for marking content provenance in agent responses. Each content block
//! carries metadata about its origin (model, tool, skill, memory, etc.)
//! enabling:
//!
//! - **Attribution**: Which model/tool/skill produced each part of the response.
//! - **Trust scoring**: Content from verified skills scores higher than unknown.
//! - **Audit trails**: Full provenance chain for compliance and debugging.
//!
//! ## Architecture
//!
//! `ProvenanceMarker` inspects content and its execution context to tag
//! each block with a `ProvenanceLabel`. Instead of substring matching
//! (brittle, O(n×m) patterns), it uses the capability graph from
//! `PromptNamespace` and tool execution records.
//!
//! ## Capability Detection
//!
//! ```text
//! For each content block:
//!   1. Check tool execution log → tag as ToolOutput(tool_name, skill_id)
//!   2. Check if content is from a memory fragment → tag as Memory(collection)
//!   3. Check if content matches skill-provided patterns → tag as SkillOutput(skill_id)
//!   4. Default → tag as ModelGenerated(model_name)
//! ```

use std::collections::{HashMap, HashSet};
use serde::{Deserialize, Serialize};

/// The origin/source of a content block.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProvenanceSource {
    /// Generated by the LLM model.
    ModelGenerated {
        model: String,
        provider: String,
    },
    /// Output from a tool execution.
    ToolOutput {
        tool_name: String,
        /// Which skill owns this tool (if any).
        skill_id: Option<String>,
    },
    /// Retrieved from memory/knowledge base.
    Memory {
        collection: String,
        chunk_id: Option<String>,
    },
    /// Injected by a skill's prompt fragment.
    SkillInjected {
        skill_id: String,
        trust_level: TrustLevel,
    },
    /// System-generated content (e.g., error messages, guardrails).
    System {
        component: String,
    },
    /// Content received from another agent via A2A inter-session delegation.
    InterSession {
        /// The agent ID that produced this content.
        source_agent: String,
        /// The session key of the originating session.
        source_session: String,
        /// The A2A task ID (if routed through the task system).
        task_id: Option<String>,
    },
    /// Origin could not be determined.
    Unknown,
}

/// Trust level for provenance attribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum TrustLevel {
    /// Core system components — highest trust.
    Core = 4,
    /// Verified/signed skills.
    Verified = 3,
    /// Community skills with review.
    Community = 2,
    /// Unverified skills.
    Unverified = 1,
    /// Unknown origin — lowest trust.
    Unknown = 0,
}

impl TrustLevel {
    pub fn from_label(label: &str) -> Self {
        match label.to_lowercase().as_str() {
            "core" | "builtin" | "system" => Self::Core,
            "verified" | "signed" | "official" => Self::Verified,
            "community" | "reviewed" => Self::Community,
            "unverified" | "user" | "custom" => Self::Unverified,
            _ => Self::Unknown,
        }
    }
}

/// A content block with provenance metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenancedContent {
    /// The content text.
    pub content: String,
    /// Provenance source.
    pub source: ProvenanceSource,
    /// Trust level (derived from source).
    pub trust: TrustLevel,
    /// Confidence in the provenance attribution (0.0–1.0).
    pub confidence: f64,
}

/// Record of a tool execution for provenance tracking.
#[derive(Debug, Clone)]
pub struct ToolExecutionRecord {
    pub tool_name: String,
    pub tool_call_id: String,
    pub skill_id: Option<String>,
    pub output_hash: u64,
}

/// Provenance marker — tags content blocks with their origin.
///
/// Uses capability-based detection via:
/// - Tool execution records (which tool produced what)
/// - Skill namespace capabilities (which skill owns which tools)
/// - Memory retrieval records
pub struct ProvenanceMarker {
    /// Model name for current session.
    model: String,
    /// Provider name for current session.
    provider: String,
    /// Tool execution log: tool_call_id → record.
    tool_log: HashMap<String, ToolExecutionRecord>,
    /// Skill → set of tool names it owns.
    skill_tools: HashMap<String, HashSet<String>>,
    /// Skill → trust level.
    skill_trust: HashMap<String, TrustLevel>,
    /// Memory chunk IDs that were injected.
    memory_chunks: HashSet<String>,
    /// Collection name for memory chunks.
    memory_collection: String,
}

impl ProvenanceMarker {
    pub fn new(model: impl Into<String>, provider: impl Into<String>) -> Self {
        Self {
            model: model.into(),
            provider: provider.into(),
            tool_log: HashMap::new(),
            skill_tools: HashMap::new(),
            skill_trust: HashMap::new(),
            memory_chunks: HashSet::new(),
            memory_collection: String::new(),
        }
    }

    /// Register a skill's tool capabilities.
    pub fn register_skill(
        &mut self,
        skill_id: &str,
        tools: HashSet<String>,
        trust: TrustLevel,
    ) {
        self.skill_tools.insert(skill_id.to_string(), tools);
        self.skill_trust.insert(skill_id.to_string(), trust);
    }

    /// Record a tool execution for later provenance attribution.
    pub fn record_tool_execution(&mut self, record: ToolExecutionRecord) {
        self.tool_log
            .insert(record.tool_call_id.clone(), record);
    }

    /// Register memory chunks that were injected into the prompt.
    pub fn register_memory_chunks(
        &mut self,
        collection: &str,
        chunk_ids: impl IntoIterator<Item = String>,
    ) {
        self.memory_collection = collection.to_string();
        for id in chunk_ids {
            self.memory_chunks.insert(id);
        }
    }

    /// Attribute provenance to a tool result content block.
    pub fn attribute_tool_result(
        &self,
        tool_call_id: &str,
    ) -> ProvenancedContent {
        if let Some(record) = self.tool_log.get(tool_call_id) {
            let skill_id = record.skill_id.clone();
            let trust = skill_id
                .as_ref()
                .and_then(|sid| self.skill_trust.get(sid))
                .copied()
                .unwrap_or(TrustLevel::Unknown);

            ProvenancedContent {
                content: String::new(), // caller fills in
                source: ProvenanceSource::ToolOutput {
                    tool_name: record.tool_name.clone(),
                    skill_id,
                },
                trust,
                confidence: 1.0, // tool executions have certain provenance
            }
        } else {
            ProvenancedContent {
                content: String::new(),
                source: ProvenanceSource::Unknown,
                trust: TrustLevel::Unknown,
                confidence: 0.0,
            }
        }
    }

    /// Attribute provenance to model-generated content.
    pub fn attribute_model_content(&self, content: String) -> ProvenancedContent {
        ProvenancedContent {
            content,
            source: ProvenanceSource::ModelGenerated {
                model: self.model.clone(),
                provider: self.provider.clone(),
            },
            trust: TrustLevel::Core,
            confidence: 0.9,
        }
    }

    /// Attribute provenance to a memory-retrieved fragment.
    pub fn attribute_memory(
        &self,
        content: String,
        chunk_id: Option<String>,
    ) -> ProvenancedContent {
        ProvenancedContent {
            content,
            source: ProvenanceSource::Memory {
                collection: self.memory_collection.clone(),
                chunk_id,
            },
            trust: TrustLevel::Verified,
            confidence: 1.0,
        }
    }

    /// Attribute provenance to content received from another agent via A2A delegation.
    pub fn attribute_inter_session(
        &self,
        content: String,
        source_agent: &str,
        source_session: &str,
        task_id: Option<String>,
    ) -> ProvenancedContent {
        ProvenancedContent {
            content,
            source: ProvenanceSource::InterSession {
                source_agent: source_agent.to_string(),
                source_session: source_session.to_string(),
                task_id,
            },
            // Inter-session content inherits Community trust by default —
            // the caller can upgrade based on the source agent's trust level.
            trust: TrustLevel::Community,
            confidence: 0.8,
        }
    }

    /// Lookup which skill owns a given tool.
    pub fn skill_for_tool(&self, tool_name: &str) -> Option<&str> {
        for (skill_id, tools) in &self.skill_tools {
            if tools.contains(tool_name) {
                return Some(skill_id.as_str());
            }
        }
        None
    }

    /// Get the trust level for a skill.
    pub fn trust_for_skill(&self, skill_id: &str) -> TrustLevel {
        self.skill_trust
            .get(skill_id)
            .copied()
            .unwrap_or(TrustLevel::Unknown)
    }

    /// Generate a provenance summary for auditing.
    pub fn summary(&self) -> ProvenanceSummary {
        let tool_count = self.tool_log.len();
        let skill_count = self.skill_tools.len();
        let memory_count = self.memory_chunks.len();

        let trust_distribution: HashMap<TrustLevel, usize> = {
            let mut dist = HashMap::new();
            for trust in self.skill_trust.values() {
                *dist.entry(*trust).or_insert(0) += 1;
            }
            dist
        };

        ProvenanceSummary {
            model: self.model.clone(),
            provider: self.provider.clone(),
            tool_executions: tool_count,
            skills_active: skill_count,
            memory_fragments: memory_count,
            trust_distribution,
        }
    }
}

/// Summary of provenance information for a session.
#[derive(Debug, Clone)]
pub struct ProvenanceSummary {
    pub model: String,
    pub provider: String,
    pub tool_executions: usize,
    pub skills_active: usize,
    pub memory_fragments: usize,
    pub trust_distribution: HashMap<TrustLevel, usize>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trust_level_from_label() {
        assert_eq!(TrustLevel::from_label("core"), TrustLevel::Core);
        assert_eq!(TrustLevel::from_label("verified"), TrustLevel::Verified);
        assert_eq!(TrustLevel::from_label("community"), TrustLevel::Community);
        assert_eq!(TrustLevel::from_label("random"), TrustLevel::Unknown);
    }

    #[test]
    fn test_attribute_tool_result() {
        let mut marker = ProvenanceMarker::new("claude-4", "anthropic");

        let mut tools = HashSet::new();
        tools.insert("web_search".to_string());
        marker.register_skill("search-skill", tools, TrustLevel::Verified);

        marker.record_tool_execution(ToolExecutionRecord {
            tool_name: "web_search".to_string(),
            tool_call_id: "tc-1".to_string(),
            skill_id: Some("search-skill".to_string()),
            output_hash: 12345,
        });

        let provenance = marker.attribute_tool_result("tc-1");
        assert_eq!(
            provenance.source,
            ProvenanceSource::ToolOutput {
                tool_name: "web_search".to_string(),
                skill_id: Some("search-skill".to_string()),
            }
        );
        assert_eq!(provenance.trust, TrustLevel::Verified);
        assert!((provenance.confidence - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_attribute_model_content() {
        let marker = ProvenanceMarker::new("gpt-4o", "openai");
        let pc = marker.attribute_model_content("Hello!".into());
        assert_eq!(
            pc.source,
            ProvenanceSource::ModelGenerated {
                model: "gpt-4o".into(),
                provider: "openai".into(),
            }
        );
    }

    #[test]
    fn test_skill_for_tool() {
        let mut marker = ProvenanceMarker::new("claude-4", "anthropic");
        let mut tools = HashSet::new();
        tools.insert("read_file".to_string());
        tools.insert("list_dir".to_string());
        marker.register_skill("fs-skill", tools, TrustLevel::Core);

        assert_eq!(marker.skill_for_tool("read_file"), Some("fs-skill"));
        assert_eq!(marker.skill_for_tool("unknown_tool"), None);
    }

    #[test]
    fn test_provenance_summary() {
        let mut marker = ProvenanceMarker::new("claude-4", "anthropic");

        let mut tools1 = HashSet::new();
        tools1.insert("search".to_string());
        marker.register_skill("skill-1", tools1, TrustLevel::Verified);

        let mut tools2 = HashSet::new();
        tools2.insert("code_exec".to_string());
        marker.register_skill("skill-2", tools2, TrustLevel::Community);

        marker.register_memory_chunks(
            "conversations",
            vec!["chunk-1".to_string(), "chunk-2".to_string()],
        );

        marker.record_tool_execution(ToolExecutionRecord {
            tool_name: "search".to_string(),
            tool_call_id: "tc-1".to_string(),
            skill_id: Some("skill-1".to_string()),
            output_hash: 0,
        });

        let summary = marker.summary();
        assert_eq!(summary.skills_active, 2);
        assert_eq!(summary.tool_executions, 1);
        assert_eq!(summary.memory_fragments, 2);
    }

    #[test]
    fn test_unknown_tool_result() {
        let marker = ProvenanceMarker::new("claude-4", "anthropic");
        let provenance = marker.attribute_tool_result("nonexistent");
        assert_eq!(provenance.source, ProvenanceSource::Unknown);
        assert!((provenance.confidence - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_inter_session_provenance() {
        let marker = ProvenanceMarker::new("claude-4", "anthropic");
        let pc = marker.attribute_inter_session(
            "delegated result".into(),
            "worker-agent",
            "session-abc",
            Some("task-123".into()),
        );
        assert_eq!(
            pc.source,
            ProvenanceSource::InterSession {
                source_agent: "worker-agent".into(),
                source_session: "session-abc".into(),
                task_id: Some("task-123".into()),
            }
        );
        assert_eq!(pc.trust, TrustLevel::Community);
        assert!((pc.confidence - 0.8).abs() < f64::EPSILON);
    }
}
