//! Canonical token usage type.
//!
//! Single source of truth for token counts across the entire workspace.
//! All crates should import this type rather than defining their own.

use serde::{Deserialize, Serialize};

/// Token usage statistics for a single LLM invocation.
///
/// This is the canonical definition — all provider, domain, and telemetry
/// code should use this type directly or convert to/from it.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Tokens consumed by the input prompt.
    pub input_tokens: u64,
    /// Tokens generated by the model.
    pub output_tokens: u64,
    /// Tokens read from cache (prompt caching).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_read_tokens: Option<u64>,
    /// Tokens written to cache.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_write_tokens: Option<u64>,
}

impl TokenUsage {
    /// Create a usage record with only input and output counts.
    pub fn new(input_tokens: u64, output_tokens: u64) -> Self {
        Self {
            input_tokens,
            output_tokens,
            cache_read_tokens: None,
            cache_write_tokens: None,
        }
    }

    /// Total tokens (input + output).
    pub fn total(&self) -> u64 {
        self.input_tokens + self.output_tokens
    }

    /// Accumulate another usage record.
    pub fn add(&mut self, other: &TokenUsage) {
        self.input_tokens += other.input_tokens;
        self.output_tokens += other.output_tokens;
        if let Some(cr) = other.cache_read_tokens {
            *self.cache_read_tokens.get_or_insert(0) += cr;
        }
        if let Some(cw) = other.cache_write_tokens {
            *self.cache_write_tokens.get_or_insert(0) += cw;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_total() {
        let u = TokenUsage::new(100, 50);
        assert_eq!(u.total(), 150);
    }

    #[test]
    fn test_accumulate() {
        let mut a = TokenUsage::new(10, 20);
        let b = TokenUsage {
            input_tokens: 5,
            output_tokens: 15,
            cache_read_tokens: Some(3),
            cache_write_tokens: None,
        };
        a.add(&b);
        assert_eq!(a.input_tokens, 15);
        assert_eq!(a.output_tokens, 35);
        assert_eq!(a.cache_read_tokens, Some(3));
    }

    #[test]
    fn test_default() {
        let u = TokenUsage::default();
        assert_eq!(u.total(), 0);
    }
}
